### ISSUE TITLE
Improve Documentation - Configuration

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [sacconazzo/directus-utils#1]
Hey there,

loving your work of easy import/export of roles and permission.

Sadly i can't use it, since i am using directus with docker. I have a "database.db" file from the directus instance. Any way to use your script with that?

**Comment by NilsBaumgartner1994** [comment]
I am using SQLite is that helps

**Comment by sacconazzo** [comment]
Hi Nils,

What errors do you get in this case?

Giona

**Comment by sacconazzo** [comment]
Actually I don't know if it works with sqlite.
I only tested it on mysql and mssql

**Comment by NilsBaumgartner1994** [comment]
> Actually I don't know if it works with sqlite.
> I only tested it on mysql and mssql

I have overridden the config file. Can you otherwise support a path to a custom config file?

**Comment by sacconazzo** [comment]
Do you mean this configuration file?
<img width="563" alt="image" src="https://github.com/sacconazzo/directus-utils/assets/32107095/22ab53c9-5893-4f5d-8b47-15b43f9f7c43">
It might be useful to make it parameterizable..

**Comment by NilsBaumgartner1994** [comment]
Yes, exactly this file.
Either make it parametrizable or which might be easier and more flexible let the user define a path to a configuration file. And then your part would be just to read the content. Makes it in the long term more stable :-)

**Comment by NilsBaumgartner1994** [comment]
I really like your idea, I have been searching for something like this quite a bit since Directus does not support it out of the box

**Comment by sacconazzo** [comment]
Thank you very much for your feedback and helpful advice.
I think I will implement it soon and will keep you updated

**Comment by NilsBaumgartner1994** [comment]
Thank you very much 😊 looking forward to it. Keep on going.

**Comment by sacconazzo** [comment]
Hi Nils, I added this feature by managing a configuration file https://www.npmjs.com/package/directus-x#setup and the option `module`. Let me know if this can be useful and if everything is ok :)

**Comment by NilsBaumgartner1994** [comment]
I will do :-) just as a small question, are Roles also linked and migrated?
What about custom other roles, do they get overridden?

**Comment by sacconazzo** [comment]
Yes, migrations overwrite (or create) a role and related permissions. The specified role can be `public` or any custom role by specifying the _key_.

Ex.:
`npx directus-x migrate -r public`
or
`npx directus-x migrate -r 3be5ba79-cb5a-46ad-9d48-6deed781253f`

**Comment by NilsBaumgartner1994** [comment]
Astonishing that such a basic feature is missing in Directus

**Comment by sacconazzo** [comment]
Yes, it's true, it would seem like a basic functionality to be able to deploy a project in a new environment
