### ISSUE TITLE
Change module.export

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [sacconazzo/directus-utils#2]
In the latest directus version the generated migrations do not work:

```
[18:33:22.004] INFO: Running migrations...
ReferenceError: module is not defined in ES module scope
2024-02-26 18:33:26 backend-directus-master-1    | This file is being treated as an ES module because it has a '.js' file extension and '/directus/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

**Comment by sacconazzo** [comment]
Hi NilsBaumgartner1994,

Thanks for the feedback. :)

Have you tried renaming the extension of the migration autogenerated to .cjs? does it work that way?

Giona

**Comment by NilsBaumgartner1994** [comment]
> Hi NilsBaumgartner1994,
> 
> Thanks for the feedback. :)
> 
> Have you tried renaming the extension of the migration autogenerated to .cjs? does it work that way?
> 
> Giona

I have just overridden the file with the export default

**Comment by sacconazzo** [comment]
> st overridden the file w

it's working?

**Comment by NilsBaumgartner1994** [comment]
> > st overridden the file w
> 
> it's working?

Yes. Just replace „module.export = „ with

„const resource = { … }

Export default resource“

and your good to go

**Comment by sacconazzo** [comment]
I understand.. a custom configuration file could then be useful that contains, among the DB configurations, also the CommonJS option

**Comment by NilsBaumgartner1994** [comment]
The common js export is just for Directus which does not use „module.exports“ anymore.
Your own intern usage is independent of this :-)

**Comment by sacconazzo** [comment]
Hi there,
try if this works for you :)
https://www.npmjs.com/package/directus-x?activeTab=readme#setup
